site_name: Digital Attendance

theme:
  name: material
  logo: ./images/onekana-logo.png
  favicon: ./images/onekana-icon.png
  font:
    text: Prompt
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.top
    - navigation.instant

plugins:
  - search
  # - mermaid2

extra_css:
  - css/extra.css
  - https://cdn.jsdelivr.net/gh/knsv/mermaid@6.0.0/dist/mermaid.css

extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
